### PR TITLE
Add Message to inform user that there is no ticket available

### PR DESCRIPTION
**Pull request by masteradhoc**
Add Message "There are no Tickets available for this event!"

### CODE REVIEW

**Comment by bordoni** [comment]
Looks good. :+1:

**Comment by barryhughes** [comment]
Hi @masteradhoc,

Thanks for this PR!

I'm just a little worried that the message would mislead/confuse users in situations where tickets _are_ available, but just aren't available "for sale" yet. Thinking of [a related PR you submitted](https://github.com/moderntribe/event-tickets/pull/94) if both are merged then that might mean users get two messages which basically restate the same information.

I definitely see that there is still a use case for this message though - ie, when all tickets have sold out - but we'd probably need to tighten it up just a bit to ensure it only renders in that situation and not when tickets are in stock but just not on sale yet.

**Comment by masteradhoc** [comment]
Thanks @barryhughes ! May you point me to the right direction, ill update the PR if you want. Or will you take a look at the case? I think it has to be added asap because user may be more confused now ;)

**Comment by borkweb** [comment]
@masteradhoc - Like @barryhughes said, thanks for this and the other PR (#94)!

There's definitely some merit to the ideas behind both of those PRs that we'd love to comment on in a single location. Since both PRs deal with messaging for tickets - it _feels_ justifiable (in my brain) to combine both of the changesets. :smile: 

Would it be too troublesome to put the changes from this PR and #94 into a single Pull Request and then PR it against our `develop` branch rather than `release/122`? Thank you!

**Comment by masteradhoc** [comment]
Thanks @borkweb for the message. I'll do that tomorrow. Alright?

**Comment by borkweb** [comment]
That sounds great to me! Thank you, sir!

**Pull request closed without merging**
