### PR TITLE
Fix/117446 datepicker format

### PR DESCRIPTION
**Pull request by paulmskim**
For tickets:
- https://central.tri.be/issues/ 117446
- https://central.tri.be/issues/ 119017

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Sprint 6*, but this was pull requested against *release/M18.18*.

**Comment by nealfennimore** [comment]
This shouldn't go into `release/F18.3`, but that bot is having a fit when I change it. @bordoni is there something we should do on that?

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Sprint 6*, but this was pull requested against *release/M18.18*.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Sprint 6*, but this was pull requested against *release/M18.18*.

**Pull request merged**
