### PR TITLE
Fixed datepicker formats validation error on ticket start sale date

### PR DESCRIPTION
**Pull request by juanfra**
🎫 https://central.tri.be/issues/102815

The origin of the problem is in the validation script in common. Bumping version and adding readme entry to log that we solved this one.

Related: https://github.com/moderntribe/tribe-common/pull/750

### CODE REVIEW

**Comment by mitogh** [comment]
Changes seems okay however I would like @barryhughes to take another look as we have an update of min required version from `common` and if I recall correctly we flagged this type of changes based on last MR updates.

**Comment by mitogh** [comment]
cc @juanfra ⬆️

**Comment by juanfra** [comment]
Thanks @mitogh! Yeah, the version bump is basically because we need the changes on moderntribe/tribe-common#750 for this to work.

**Comment by barryhughes** [comment]
> I would like @barryhughes to take another look as we have an update of min required version from common and if I recall correctly we flagged this type of changes based on last MR updates.

Thanks for flagging! This seems A-OK to me :-)

My thinking:

* A bump to the min required version of Tribe Common is fine here, because Event Tickets ships with it anyway (we can effectively guarantee that at least this version will be present and loaded)
* It's changes in the min required version of _other_ plugins that is more problematic during MRs (ie, if the min required version of TEC changes for PRO, because we can't guarantee that TEC will also be updated at the same time, etc)

**Pull request merged**
