### PR TITLE
⌗117794 Restoring ET Welcome Page Refresh Code

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**⌗117794**](http://central.tri.be/issues/117794)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'Tribe__Tickets__Main' | [admin-welcome-message.php:7](https://github.com/moderntribe/event-tickets/blob/69221f61a749bd56b1938f6f712ca37ab0e4c98e/src/admin-views/admin-welcome-message.php#L7)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [admin-welcome-message.php:16](https://github.com/moderntribe/event-tickets/blob/69221f61a749bd56b1938f6f712ca37ab0e4c98e/src/admin-views/admin-welcome-message.php#L16)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'Tribe__Tickets__Main' | [admin-welcome-message.php:7](https://github.com/moderntribe/event-tickets/blob/a1587fde423d7653d5533111b0f39caadac99571/src/admin-views/admin-welcome-message.php#L7)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [admin-welcome-message.php:16](https://github.com/moderntribe/event-tickets/blob/a1587fde423d7653d5533111b0f39caadac99571/src/admin-views/admin-welcome-message.php#L16)

> via jenkins/codesniffer-phpcs

**Comment by ggwicz** [comment]
I've implemented Juan's feedback—this is ready for another review! 🔍

**Comment by ggwicz** [comment]
I've reset this PR to be submitted against release/G19.02 — ready for another review! 🔍

**Comment by sc0ttkclark** [comment]
I'm going to review this side by side with what we have already, will approve once I check that out.

**Pull request merged**
