### PR TITLE
Fix/68831 attendee mgmt caps

### PR DESCRIPTION
**Pull request by jesseeproductions**
_Ref:_ [C#68831](https://central.tri.be/issues/68831)

Add manage_attendees (move, delete, check in) and checkin_attendees (check in) capability and restrict actions to new capabilities. Admin and Editor have manage_attendees and Author's checkin_attendees

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Expected 1 space after &quot;=&quot;; 2 found | [Move_Tickets.php:30](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Admin/Move_Tickets.php#L30)
:x: | Expected 1 space after &quot;=&quot;; 2 found | [Attendees_Table.php:39](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Attendees_Table.php#L39)
:x: | Expected 1 space after &quot;=&quot;; 2 found | [Attendees_Table.php:411](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Attendees_Table.php#L411)
:x: | Blank line found after control structure | [Capabilities.php:91](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L91)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:107](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L107)
:x: | String concat is not required here; use a single string instead | [Capabilities.php:107](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L107)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:108](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L108)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:131](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L131)
:x: | String concat is not required here; use a single string instead | [Capabilities.php:131](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L131)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:132](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Capabilities.php#L132)
:x: | Empty CATCH statement detected | [Updater.php:59](https://github.com/moderntribe/event-tickets/blob/42707c3a116d0dbed3d2f128597c0766aea1613e/src/Tribe/Updater.php#L59)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:105](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L105)
:x: | String concat is not required here; use a single string instead | [Capabilities.php:105](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L105)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:106](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L106)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:129](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L129)
:x: | String concat is not required here; use a single string instead | [Capabilities.php:129](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L129)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Capabilities.php:130](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Capabilities.php#L130)
:x: | Empty CATCH statement detected | [Updater.php:59](https://github.com/moderntribe/event-tickets/blob/b4221f71d47b6afd2eb23c4ab63cf28967bbdcfc/src/Tribe/Updater.php#L59)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M17.18*.

**Comment by anutin544** [comment]
Ok

**Pull request closed without merging**
