### PR TITLE
get_event_attendees should filter return value to allow modification.

### PR DESCRIPTION
**Pull request by jtsternberg**

### CODE REVIEW

**Comment by barryhughes** [comment]
Hi @jtsternberg - looks like a useful change :+1:

Before we merge, would it be possible for you to [document both those hooks](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters)? Thanks!

**Comment by barryhughes** [comment]
Ticketed: [#70673](https://central.tri.be/issues/70673)

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Tickets.php:737](https://github.com/moderntribe/event-tickets/blob/37a7b0ddf331aa4930c2b45330e3d54c1773b898/src/Tribe/Tickets.php#L737)

> via jenkins/codesniffer-phpcs

**Comment by jtsternberg** [comment]
I documented the hook, and refactored the method to allow one exit point.

**Comment by bordoni** [comment]
Closed due to #317 merging this.

**Pull request closed without merging**
