### PR TITLE
VR > Map View > Add cost to tooltip

### PR DESCRIPTION
**Pull request by juanfra**
🎫 [ECP-294]
🎥 https://www.loom.com/share/f83f9ea7a515444ea1556a217f5930b3

[ECP-294]: https://moderntribe.atlassian.net/browse/ECP-294

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Should this go into G20.01 or does it go into the beta?

**Comment by bordoni** [comment]
Going to create a `release/B20.01.1` since it will be the first MR, not the main release.

**Comment by sc0ttkclark** [comment]
Needs changelog?

**Comment by juanfra** [comment]
@sc0ttkclark we're not adding changelog entries for the VR project yet. I guess we'll be doing that once we leave beta/rc.

**Pull request merged**
