### PR TITLE
VR > Init integration and add overrides for "Cost/Buy" event section.

### PR DESCRIPTION
**Pull request by juanfra**
🎫 https://central.tri.be/issues/134145

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Holding on #1360

**Comment by cliffordp** [comment]
@sc0ttkclark @juanfra My PR got merged into G19.12 so I merged G19.12 into this branch and then made the template changes. Let me know if you need anything else.

**Comment by juanfra** [comment]
Perfect, thank you both! 🎉

**Comment by juanfra** [comment]
@bordoni @sc0ttkclark this one is ready for review :)

**Pull request merged**
