### PR TITLE
Merge ORM into B19.04

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/123471
Mind that this PR is to merge the ORM branch into **Blue** team release of ET (`release/B19.04`).  
The `release/B19.04` branch is a fork of current (as of 3/6/2019) `release/G19.04`.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $use_query_builder is never used | [Attendee_Repository.php:41](https://github.com/moderntribe/event-tickets/blob/f314a01e0943c6a411f7f0e66c7c417c6423c482/src/Tribe/REST/V1/Attendee_Repository.php#L41)
:warning: | The method parameter $use_query_builder is never used | [Ticket_Repository.php:75](https://github.com/moderntribe/event-tickets/blob/f314a01e0943c6a411f7f0e66c7c417c6423c482/src/Tribe/REST/V1/Ticket_Repository.php#L75)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $use_query_builder is never used | [Attendee_Repository.php:41](https://github.com/moderntribe/event-tickets/blob/76f44fce4f376725ddb406397159c4e35fc3b667/src/Tribe/REST/V1/Attendee_Repository.php#L41)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $use_query_builder is never used | [Attendee_Repository.php:41](https://github.com/moderntribe/event-tickets/blob/84b256cdaeb34b3ef3e11027bd3ee64065881f3d/src/Tribe/REST/V1/Attendee_Repository.php#L41)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
Please note that what's not passing in this PR is not passing on G release branch too.

**Pull request merged**
