### PR TITLE
Tweaks for Buy Now Buttons

### PR DESCRIPTION
**Pull request by zbtirrell**
Fixes:
* check for tickets being on sale before showing CTAs
* change stock text for RSVPs
* fix the sold-out-html
* fix number formatting

See: https://central.tri.be/issues/79024

There are more fixes to be done for the associated ticket.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [tickets.php:289](https://github.com/moderntribe/event-tickets/blob/4fbf8052ad10c3c3d2b5de54df50bc9911c33609/src/template-tags/tickets.php#L289)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [tickets.php:289](https://github.com/moderntribe/event-tickets/blob/eb71626bdb538d9c06351ad6054dbb5223ce0d32/src/template-tags/tickets.php#L289)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Sidenote unrelated to your specific change here, `tribe_tickets_display_count_and_ticket_button()` declares the wrong return type (always `null`) in the docblock.

**Comment by barryhughes** [comment]
:potable_water:

**Pull request merged**
