### PR TITLE
Restore tests

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: #91173

This PR:
* restore tests from the `bucket/tribe-commerce` branch
* adds and configures the `acceptance` suite
* extends the `tests.md` file for more acceptance information

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1779](https://github.com/moderntribe/event-tickets/blob/e3f7ad49410c8c3a2c9765d4fb4e3be8466f9ebc/src/Tribe/RSVP.php#L1779)
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1251](https://github.com/moderntribe/event-tickets/blob/e3f7ad49410c8c3a2c9765d4fb4e3be8466f9ebc/src/Tribe/Tickets.php#L1251)
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1261](https://github.com/moderntribe/event-tickets/blob/e3f7ad49410c8c3a2c9765d4fb4e3be8466f9ebc/src/Tribe/Tickets.php#L1261)
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1264](https://github.com/moderntribe/event-tickets/blob/e3f7ad49410c8c3a2c9765d4fb4e3be8466f9ebc/src/Tribe/Tickets.php#L1264)
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1276](https://github.com/moderntribe/event-tickets/blob/e3f7ad49410c8c3a2c9765d4fb4e3be8466f9ebc/src/Tribe/Tickets.php#L1276)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1779](https://github.com/moderntribe/event-tickets/blob/5a0ff6cef3fe118998c522e7de7c7160b2c719d1/src/Tribe/RSVP.php#L1779)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1779](https://github.com/moderntribe/event-tickets/blob/095a47f810df940181c2e9579dae1edd7414e355/src/Tribe/RSVP.php#L1779)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1779](https://github.com/moderntribe/event-tickets/blob/77f4e066cd997b585cd046c4a9881ec8aeb0eaba/src/Tribe/RSVP.php#L1779)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
While I cannot see the Travis work log the tests did pass; this is ready for a review.

**Pull request merged**
