### PR TITLE
Display the ticket icon according to the date of the event 

### PR DESCRIPTION
**Pull request by juanfra**
🎫 https://central.tri.be/issues/115802

**📹 Screencast**
https://www.useloom.com/share/4f030baa968f44349483a8e29a5fa5e6

### CODE REVIEW

**Comment by juanfra** [comment]
Thanks @paulmskim ! 

When you mention the requirements of the ticket you mean this? https://central.tri.be/issues/115802#note-22

I think, by definition a ticket will be scheduled if the start date of the ticket is actually > of the current moment. The icon is meant to display what the person is actually doing, if they change the date, and it's in the future, they see a clock. If the current date is within a ticket date params, then we need to show a ticket. Perhaps we can get some sort of clarification from strategy. If they set a ticket with a date from a day before, I assume the user would like to see a ticket and not a clock, and that's what it's doing.

Technically speaking, do you see something that's purely wrong? Or some code that can break stuff?

**Comment by paulmskim** [comment]
Ah I did not see that note. However, that doesn't change my interpretation of the strategy. So how I'm understanding it is that "if the duration is manually adjusted", meaning if the start date, start time, end date, or end time is altered in any way, regardless of whether it's backwards or forwards, it should show the clock icon. It also requires the ticket to be created to display, which right now we do not have a check for. Would love to hop on a call to clarify this.

**Comment by juanfra** [comment]
https://www.useloom.com/share/fefaecc6ecf84841af4be8d3468ada8c

**Comment by juanfra** [comment]
Thanks @nealfennimore!

Ended up using `isMoment` as it's more reliable.

**Pull request merged**
