### PR TITLE
restore all tests

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/97919

Restore all the tests on the plugin

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/259f17b188cc41b20234fbfacd3ad216a216b2eb/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/259f17b188cc41b20234fbfacd3ad216a216b2eb/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/259f17b188cc41b20234fbfacd3ad216a216b2eb/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/259f17b188cc41b20234fbfacd3ad216a216b2eb/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/259f17b188cc41b20234fbfacd3ad216a216b2eb/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/18366deb973b96bea9cff75e198941a922a6d701/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/18366deb973b96bea9cff75e198941a922a6d701/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/18366deb973b96bea9cff75e198941a922a6d701/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/18366deb973b96bea9cff75e198941a922a6d701/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/18366deb973b96bea9cff75e198941a922a6d701/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/c6b417452ebc648090af5de31eac8818b54b64a7/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/c6b417452ebc648090af5de31eac8818b54b64a7/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/c6b417452ebc648090af5de31eac8818b54b64a7/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/c6b417452ebc648090af5de31eac8818b54b64a7/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/c6b417452ebc648090af5de31eac8818b54b64a7/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/4d0b7793b25ff203540c5821081742a7e5145ff6/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/4d0b7793b25ff203540c5821081742a7e5145ff6/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/4d0b7793b25ff203540c5821081742a7e5145ff6/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/4d0b7793b25ff203540c5821081742a7e5145ff6/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/4d0b7793b25ff203540c5821081742a7e5145ff6/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/f7da1904461fcf00588aa779ccf9f4076dc4fd11/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/f7da1904461fcf00588aa779ccf9f4076dc4fd11/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/f7da1904461fcf00588aa779ccf9f4076dc4fd11/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/f7da1904461fcf00588aa779ccf9f4076dc4fd11/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/f7da1904461fcf00588aa779ccf9f4076dc4fd11/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/f52032c5b4bf2a218e31b27b7bf994ace9a5b1a7/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/f52032c5b4bf2a218e31b27b7bf994ace9a5b1a7/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/f52032c5b4bf2a218e31b27b7bf994ace9a5b1a7/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/f52032c5b4bf2a218e31b27b7bf994ace9a5b1a7/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/f52032c5b4bf2a218e31b27b7bf994ace9a5b1a7/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/583164732e274b4a21bcf2557d044763824067b3/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/583164732e274b4a21bcf2557d044763824067b3/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/583164732e274b4a21bcf2557d044763824067b3/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/583164732e274b4a21bcf2557d044763824067b3/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/583164732e274b4a21bcf2557d044763824067b3/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1788](https://github.com/moderntribe/event-tickets/blob/1b409547cb96d77959c96868f352dbdada38ddb9/src/Tribe/RSVP.php#L1788)
:x: | There must be a single space after the first square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/1b409547cb96d77959c96868f352dbdada38ddb9/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space before the last square bracket | [RSVP.php:1915](https://github.com/moderntribe/event-tickets/blob/1b409547cb96d77959c96868f352dbdada38ddb9/src/Tribe/RSVP.php#L1915)
:x: | There must be a single space after the first square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/1b409547cb96d77959c96868f352dbdada38ddb9/src/Tribe/RSVP.php#L1919)
:x: | There must be a single space before the last square bracket | [RSVP.php:1919](https://github.com/moderntribe/event-tickets/blob/1b409547cb96d77959c96868f352dbdada38ddb9/src/Tribe/RSVP.php#L1919)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/d2ce7daeb7e3c82608d30409ea696d1cce59e5f5/src/Tribe/RSVP.php#L1794)
:x: | There must be a single space after the first square bracket | [RSVP.php:1921](https://github.com/moderntribe/event-tickets/blob/d2ce7daeb7e3c82608d30409ea696d1cce59e5f5/src/Tribe/RSVP.php#L1921)
:x: | There must be a single space before the last square bracket | [RSVP.php:1921](https://github.com/moderntribe/event-tickets/blob/d2ce7daeb7e3c82608d30409ea696d1cce59e5f5/src/Tribe/RSVP.php#L1921)
:x: | There must be a single space after the first square bracket | [RSVP.php:1925](https://github.com/moderntribe/event-tickets/blob/d2ce7daeb7e3c82608d30409ea696d1cce59e5f5/src/Tribe/RSVP.php#L1925)
:x: | There must be a single space before the last square bracket | [RSVP.php:1925](https://github.com/moderntribe/event-tickets/blob/d2ce7daeb7e3c82608d30409ea696d1cce59e5f5/src/Tribe/RSVP.php#L1925)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
Tests all green, ready for code review.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/bf9f77652b4536c82d18b64693debe38714399ff/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/2ccfa6ecabaaa4da2fc0b0726490601f6543f35c/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/3ec33538f0888f2130b87b61173a6ef0a25fadd0/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/1a6461547d8ba9c3289b21fa1c3d47670b7c04a3/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/9b3cb6b6f743dbcef5133b4314f4c5951c7896f5/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [RSVP.php:1794](https://github.com/moderntribe/event-tickets/blob/f7ed7267489e81a7e0e8c4e175d48fb9b2e03217/src/Tribe/RSVP.php#L1794)

> via jenkins/codesniffer-phpcs

**Pull request merged**
