### PR TITLE
95257 Prevent Overriding of Start|End Sale Dates on RSVPs and Tickets

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**#95257**](http://central.tri.be/issues/95257)

### CODE REVIEW

**Comment by bordoni** [comment]
On this one @ggwicz we need to make sure we are validating if there were any manual changes to the sales DateTime on the ticket or RSVP, because otherwise it's the intended behavior to prevent fails of tickets with no Start and End.

**Comment by mitogh** [comment]
I think this is the same as #699

**Comment by ggwicz** [comment]
It looks so!

**Comment by mitogh** [comment]
💃

**Pull request closed without merging**
