### PR TITLE
Fix/1007336 unify upsell

### PR DESCRIPTION
**Pull request by niconerd**
https://central.tri.be/issues/100736

Created branch from _release/F17.9_ as the text I modified is for Tribe Commerce and that code hasn't been merged into the MR branch yet. Please let me know if this wasn't the correct approach.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (like esc_html_e() or esc_attr_e()), not '_e' | [Attendees_Table.php:779](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Attendees_Table.php#L779)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$tabbed_view' | [Orders_Tabbed_View.php:94](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/Orders_Tabbed_View.php#L94)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '&quot;
' | [Attendance_Totals.php:76](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Attendance_Totals.php#L76)
:x: | There must be a single space after the first parenthesis | [Endpoints.php:28](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Endpoints.php#L28)
:x: | There must be a single space before the last parenthesis | [Endpoints.php:28](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Endpoints.php#L28)
:x: | No space found after comma in function call | [Endpoints.php:28](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Endpoints.php#L28)
:x: | die must follow wp_safe_redirect | [Endpoints.php:37](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Endpoints.php#L37)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$form' | [Tickets_Form.php:109](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php#L109)
:x: | There must be a single space before the last parenthesis | [Gateway.php:361](https://github.com/moderntribe/event-tickets/blob/5d8d63fe2ab4994e032629583f8d88b45f344f6d/src/Tribe/Commerce/PayPal/Gateway.php#L361)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
> Created branch from release/F17.9 as the text I modified is for Tribe Commerce and that code hasn't been merged into the MR branch yet.

If we want it to ship in F17.9, that's the branch to target (the ticket description suggests it's a small change so that probably makes sense if you can).

If that branch is in code freeze, though, let's wait until F17.9 has launched and been merged into master before proceeding.

**Comment by niconerd** [comment]
> If that branch is in code freeze, though, let's wait until F17.9 has launched and been merged into master before proceeding.
Yes, this is the case. Let's wait then.

**Comment by bordoni** [comment]
@niconerd can you re-open this PR with the code again? It seems odd that it's showing all of Tribe Commere in the Diff here.

**Pull request closed without merging**
