### PR TITLE
Simplify event summary info in attendee screen

### PR DESCRIPTION
**Pull request by barryhughes**
Simplifies and makes it easier to extend aspects of the summary box (in the attendee screen).

[C#61992](https://central.tri.be/issues/61992)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Tickets_Handler.php:84](https://github.com/moderntribe/event-tickets/blob/47254c697bf56bcd9e6bb51d7ce5a56e43deacfc/src/Tribe/Tickets_Handler.php#L84)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
> Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' 
> Tickets_Handler.php:84

⬑ Deliberate: we're printing out HTML here so we don't wish to escape.

**Comment by barryhughes** [comment]
Further changes added.

**Comment by borkweb** [comment]
:+1:

**Pull request merged**
