### PR TITLE
Settings UI

### PR DESCRIPTION
**Pull request by Camwyn**
Ticket: https://central.tri.be/issues/80618
Set out all the UI for settings panel, most of it working. Saving covered in 80624

Requires https://github.com/moderntribe/event-tickets-plus/pull/341

Includes latest master branch ( separate PR for that here: https://github.com/moderntribe/event-tickets/pull/397 )

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$header_img' | [meta-box.php:252](https://github.com/moderntribe/event-tickets/blob/896cfce7c25176409d4a253f5e08399df92713cf/src/admin-views/meta-box.php#L252)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
> Includes latest master branch ( separate PR for that here: #397 )

Looks like that was merged: does this branch need to be synced with the latest `bucket/ticket-editor-refresh` code? Might give us a cleaner view of the issue-specific changes.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$header_img' | [meta-box.php:252](https://github.com/moderntribe/event-tickets/blob/46d5c762e6b8b08478df64c537f168e007660ac4/src/admin-views/meta-box.php#L252)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$header_img' | [meta-box.php:252](https://github.com/moderntribe/event-tickets/blob/d392586536cb680d1f89c0cc5326790ae3e027b5/src/admin-views/meta-box.php#L252)

> via jenkins/codesniffer-phpcs

**Pull request merged**
