### PR TITLE
Add expanded capacity display table

### PR DESCRIPTION
**Pull request by Camwyn**
Ticket: https://central.tri.be/issues/80619

Adds a table displaying capacity to settings panel.

Requires: https://github.com/moderntribe/event-tickets-plus/pull/342 (ET+)
Requires: https://github.com/moderntribe/event-tickets/pull/397 (merge master in separately)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$ticket' | [list.php:54](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/list.php#L54)
:warning: | Comment refers to a TODO task &quot;this should get moved to Community Events? Use tribe_events_tickets_pre_edit&quot; | [meta-box.php:102](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L102)
:warning: | Comment refers to a TODO task &quot;Do these need to get renamed for RSVPs?&quot; | [meta-box.php:114](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L114)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [meta-box.php:141](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L141)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$startHourOptions' | [meta-box.php:143](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L143)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$startMinuteOptions' | [meta-box.php:146](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L146)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$startMeridianOptions' | [meta-box.php:150](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L150)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [meta-box.php:160](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L160)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$endHourOptions' | [meta-box.php:162](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L162)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$endMinuteOptions' | [meta-box.php:165](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L165)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$endMeridianOptions' | [meta-box.php:169](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L169)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$header_img' | [meta-box.php:242](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L242)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$header_img' | [meta-box.php:242](https://github.com/moderntribe/event-tickets/blob/e75b01b4d3a942143e3f054ba319ccda7297bd79/src/admin-views/meta-box.php#L242)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
It looks like the MR was merged into this branch and is a part of this pull request? If so, it'd be better to merge the MR (`master`) in a separate PR to keep this one clean.

**Comment by Camwyn** [comment]
@borkweb You are correct sir: https://github.com/moderntribe/event-tickets/pull/397

**Comment by Camwyn** [comment]
Closing in favor of https://github.com/moderntribe/event-tickets/pull/399

**Pull request closed without merging**
