### PR TITLE
'Total sold' should equal the sum of 'finalized' and 'pending' | #45538

### PR DESCRIPTION
**Pull request by barryhughes**
Fixes the attendee screen arithmetic. Replaces method of reckoning how many attendees were deleted with actual tracking of that figure.

https://central.tri.be/issues/45538

### CODE REVIEW

**Comment by borkweb** [comment]
👌

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Attendance.php:27](https://github.com/moderntribe/event-tickets/blob/ef1b40b694fe32a3b5c6ada40f5af09be7aac49e/src/Tribe/Attendance.php#L27)
:x: | Whitespace found at end of line | [Attendance.php:29](https://github.com/moderntribe/event-tickets/blob/ef1b40b694fe32a3b5c6ada40f5af09be7aac49e/src/Tribe/Attendance.php#L29)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Setting back to `code review` - the original change re 'total sold' arithmetic is still here, but I've added code to track deleted attendees (and if approved will follow up with a PR for ET+ that uses this approach in a safe way).

**Comment by borkweb** [comment]
This looks good. I like the `qty_getter_setter()` method.

🎈

**Comment by barryhughes** [comment]
Thanks! Originally that was because I added a `qty_deleted()` method and realized we had precisely the same logic 3-times over. That was removed, but yeah seemed to make sense to keep the approach for the other two `qty_*()` methods.

**Pull request merged**
