### PR TITLE
Don't remove items from the array, just fetch them

### PR DESCRIPTION
**Pull request by Camwyn**
🎫 https://central.tri.be/issues/96538
We (OK, *I* - it was totally me!) were using `array_shift` which removes the item from the array.

So, when we came back around to compare later (like when we used the example filter from the ticket), that item was no longer in the array and the condition wouldn't trigger.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1261](https://github.com/moderntribe/event-tickets/blob/1629e903c0bd7c5f4a86799366ee913ac61d017f/src/Tribe/Tickets.php#L1261)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Tribe Commerce*, but this was pull requested against *release/17.9*.

**Comment by bordoni** [comment]
Fixed, we needed to change the Milestone Description to match.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Tribe Commerce*, but this was pull requested against *release/17.9*.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Tribe Commerce*, but this was pull requested against *release/17.9*.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Must use &quot;self::&quot; for local static member reference | [Tickets.php:1261](https://github.com/moderntribe/event-tickets/blob/1d6f75fce86004e0814488679c03e4d3e93a4736/src/Tribe/Tickets.php#L1261)

> via jenkins/codesniffer-phpcs

**Pull request merged**
