### PR TITLE
Just JS formatting tweaks

### PR DESCRIPTION
**Pull request by cliffordp**
[ETP-34]

[ETP-34]: https://moderntribe.atlassian.net/browse/ETP-34

### CODE REVIEW

**Comment by cliffordp** [comment]
@sc0ttkclark do you really want me to fix all the ESLint failures? happy to if you say so but wanted to check, since it prefers `let` instead of `var` and other things...

**Comment by Camwyn** [comment]
> since it prefers `let` instead of `var`
IE11 supports let and const, so we should be shifting in that direction.
@paulmskim  opinions?

**Comment by sc0ttkclark** [comment]
I think the direction here in fixing eslint issues should be fine

**Comment by cliffordp** [comment]
Awaiting merge of https://github.com/moderntribe/event-tickets/pull/1548 before to fix linting errors (if any remain) in this branch

**Comment by paulmskim** [comment]
> > since it prefers `let` instead of `var`
> 
> IE11 supports let and const, so we should be shifting in that direction.
> @paulmskim opinions?

@Camwyn no strong opinions here, but we should discuss this in a FE related discussion. I'm not sure how agency deals with this, though they use webpack to compile so it ends up not mattering. Products should at least try to work in the same direction.

**Comment by cliffordp** [comment]
@sc0ttkclark should this have a 'hold' label or be merged as-is awaiting follow-up PR since it's at least better than it was?

**Comment by sc0ttkclark** [comment]
Pretty sure @Camwyn's work in #1548 covers this. Please open a new PR if you want to address anything further (merge conflicts galore here)

**Pull request closed without merging**
