### PR TITLE
Support Singular form of Ticket Description

### PR DESCRIPTION
**Pull request by solepixel**

### CODE REVIEW

**Comment by solepixel** [comment]
Merged!

**Comment by sc0ttkclark** [comment]
Thanks @solepixel :)

**Comment by jrserani** [comment]
_Ref:_ [C#129582](http://central.tri.be/issues/129582)

@solepixel thank you for submitting this - we'll let you know if we have any questions or comments :-)

**Comment by sc0ttkclark** [comment]
We are merging this into our own branch which we will put into our upcoming release from there. We'll update this PR with a link to that branch when that PR is created.

**Pull request merged**
