### PR TITLE
Load PUE when having invalid versions

### PR DESCRIPTION
**Pull request by bordoni**
_Ref:_ [C#119262](http://central.tri.be/issues/119262)
---

### CODE REVIEW

**Comment by jesseeproductions** [comment]
Please add a readme entry as this will be the only change for ET in 18.17

**Comment by juanfra** [comment]
Should we deprecate `maybe_include_et_plus_file` instead of just renaming the method? I see in the todo that is supposed to disappear. Just asking.

**Comment by bordoni** [comment]
@juanfra  no need, it's a Private method.

**Comment by juanfra** [comment]
Right, didn't see that. I'm burnt out!

**Pull request merged**
