### PR TITLE
conditionally update the ticket cache

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/63959

This PR adds a check to make sure TEC and PRO related actions are not attempted when the plugins are not active.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first parenthesis | [Tickets.php:532](https://github.com/moderntribe/event-tickets/blob/71761e1a68379fd00510fbe4e875bcf62a7b3ab0/src/Tribe/Tickets.php#L532)
:x: | There must be a single space before the last parenthesis | [Tickets.php:532](https://github.com/moderntribe/event-tickets/blob/71761e1a68379fd00510fbe4e875bcf62a7b3ab0/src/Tribe/Tickets.php#L532)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Guessing this is because `Tribe__Tickets__Tickets::maybe_update_attendees_cache()` calls `tribe_is_event()`.

When I look at `Tribe__Tickets__Tickets::get_event_attendees()` though (which gets/sets the cached value) it doesn't seem to care whether the 'event' is an actual `'tribe_event'` post or not - so what I'm wondering is: do we need these checks, or should we adjust `Tribe__Tickets__Tickets::maybe_update_attendees_cache()` and remove the `tribe_is_event()` call?

**Comment by lucatume** [comment]
I think the call should be removed entirely and re-instate the cache update.
Tickets could be associated to any post type, not just events, and we want to update cache for any post type.

**Comment by barryhughes** [comment]
:8ball:

**Pull request merged**
