### PR TITLE
Merge release/G19.03 into bucket/orm branch

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: n/a

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [View.php:60](https://github.com/moderntribe/event-tickets/blob/0dd2e4bcf3c524373c00b6b7c97c1349cf1e688a/src/Tribe/Attendee_Registration/View.php#L60)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [View.php:60](https://github.com/moderntribe/event-tickets/blob/7ae6e2fe73b9ac14af7e279032167cf7e0134be1/src/Tribe/Attendee_Registration/View.php#L60)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [View.php:60](https://github.com/moderntribe/event-tickets/blob/d296077e66a9e5d05766393fbe09deb8a52b6141/src/Tribe/Attendee_Registration/View.php#L60)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [View.php:60](https://github.com/moderntribe/event-tickets/blob/9d6b1e389fd33ee1abca19b549511674d65348fe/src/Tribe/Attendee_Registration/View.php#L60)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
@sc0ttkclark could I get your review on this? I, especially, would like to have your heads-up on the fact I've deactivated `functional` and `restv1` tests while fixing them on other PRs.

**Pull request merged**
