### PR TITLE
Fix/120280 ticket independent capacity

### PR DESCRIPTION
**Pull request by paulmskim**
For ticket: https://central.tri.be/issues/120280

### CODE REVIEW

**Comment by paulmskim** [comment]
@bordoni @mitogh could you have a look at this, since you guys wrote this REST class? I need to know that the only place that we use the function at https://github.com/moderntribe/event-tickets/pull/1076/files#diff-463c06e997679576351abf66c1481112R211 is in the REST API for the block editor, so that doing https://github.com/moderntribe/event-tickets/pull/1076/files#diff-463c06e997679576351abf66c1481112R279 is OK as long as the block editor handles it.

**Comment by paulmskim** [comment]
@bordoni @mitogh a quick reminder here on the question above.

**Comment by mitogh** [comment]
Sorry for the delay on this one @paulmskim .

And this one was created specifically for this new use case (Gutenberg) as the old system was using `admin-ajax` call inside of the editor.

And this is the code related to the old editor.

https://github.com/moderntribe/event-tickets/blob/eab57107fb59f6b21d98f74b8d6b2053e7661111/src/Tribe/Metabox.php#L184

Created by this action.

https://github.com/moderntribe/event-tickets/blob/eab57107fb59f6b21d98f74b8d6b2053e7661111/src/Tribe/Metabox.php#L24

Let me know if you have additional questions about this.

Thanks.

**Comment by sc0ttkclark** [comment]
Can you confirm whether this is ready to be reviewed officially yet?

**Comment by paulmskim** [comment]
@sc0ttkclark this is ready for review.

**Pull request merged**
