### PR TITLE
98750 Factor Refunds into "Sold" and "Remaining" Counts

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**#98750**](http://central.tri.be/issues/98750)

### CODE REVIEW

**Comment by bordoni** [comment]
@ggwicz  agree here with @zbtirrell  we might need to punt this one to the next MR, and give it a little bit of Strategy look.

**Comment by ggwicz** [comment]
Alright, I've left a strategy question on the ticket and will update accordingly. https://central.tri.be/issues/98750#note-19

**Comment by zbtirrell** [comment]
Leah is working on detailed strategy that directly relates to this in another ticket: https://central.tri.be/issues/73733

I think we should deal with both at the same time.

This particular pull request is adjusting the number at the wrong spot though, so, I think it should be closed.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *M18.06*, but this was pull requested against *release/M18.05*.

**Pull request closed without merging**
