### PR TITLE
Message: Tickets are no longer or not yet on sale

### PR DESCRIPTION
**Pull request by masteradhoc**
My PullRequest comes from here:
https://theeventscalendar.com/support/forums/topic/no-message-end-date-for-sales-reached/

I think the user should be informed when tickets are no longer on sale. I would love to also code this for "woocommerce" and "easy digital downloads". May you allow me to see those files? i'll add the code asap.

Thanks

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Ticket_Object.php:199](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L199)
:x: | Whitespace found at end of line | [Ticket_Object.php:213](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L213)
:x: | Whitespace found at end of line | [Ticket_Object.php:218](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L218)
:x: | There must be a single space before the last parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | No space after opening parenthesis is prohibited | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | There must be a single space after the first parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | There must be a single space after the first parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | There must be a single space before the last parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | There must be a single space after the first parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | There must be a single space before the last parenthesis | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | No space before closing parenthesis is prohibited | [Ticket_Object.php:219](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L219)
:x: | Whitespace found at end of line | [Ticket_Object.php:224](https://github.com/moderntribe/event-tickets/blob/271e465c733edeff9bdb6de2a07a102ce575f9f3/src/Tribe/Ticket_Object.php#L224)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Ticket_Object.php:199](https://github.com/moderntribe/event-tickets/blob/8ca3eed1f299cc2f7aff636032ee2f6d10b7cf6d/src/Tribe/Ticket_Object.php#L199)

> via jenkins/codesniffer-phpcs

**Comment by masteradhoc** [comment]
@borkweb May you could take a look at this PR? I cant work out the missing ticket reference ;) Thanks

**Comment by zbtirrell** [comment]
@masteradhoc no worries on the ticket reference.  That is for internal purposes only (I should update the bot to be clear about that).  A Modern Tribe rep will add that for you at some point before this gets merged.

**Pull request closed without merging**
