### PR TITLE
Tickets left display threshold

### PR DESCRIPTION
**Pull request by JoryHogeveen**
#119910

Currently there is no way to change the threshold to display "# tickets left" beside the price.
This PR adds a new setting and a filter `tribe_tickets_left_threshold` to optionally change this threshold.

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
- Ticket ref check: Where can I create a ticket? It seems disabled in this repo.
- Travis errors: These errors aren't related to my changes.

**Comment by sc0ttkclark** [comment]
Love this!

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Tickets are in our own private ticket system, we'll handle that for you. Don't worry about those specific Travis errors, we're working on that.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark  Ok perfect!
Last commit changed the names of the setting, filter and label to a more unified approach.

**Comment by jrserani** [comment]
_Ref:_ [C#119910](https://central.tri.be/issues/119910)

@JoryHogeveen - thank you for your first PR to Event Tickets! We appreciate the time you took to help make the plugin even better. We have this now added to our workflow and we'll let you know if we have any questions. :-)

**Comment by sc0ttkclark** [comment]
Just an update @JoryHogeveen, this is on my list this week so look for it to be merged within the next few days into our next maintenance release.

**Comment by JoryHogeveen** [comment]
Thanks @sc0ttkclark !

**Comment by JoryHogeveen** [comment]
Update on this?

**Comment by sc0ttkclark** [comment]
As per our convo on Slack, this is on our next release. We were focused on addressing bug fixes the past few releases and enhancements like these had been prioritized. I'm bringing it back into our next release (G19.04) as our dev cycle is closing today for the current release (G19.03). All we need to do here is add an automated test for this new option to ensure it works as expected long term. We're resolving other testing environment issues we've had with Travis and Nginx lately so it'll be a good time to get a test written and passing for this too.

**Comment by JoryHogeveen** [comment]
Thanks for the update @sc0ttkclark!

**Pull request merged**
